/**
 * scan.model.ts
 * ─────────────
 * All TypeScript interfaces / types shared across the scan feature.
 * No runtime logic lives here — pure type definitions only.
 */

// ── Inbound request body ─────────────────────────────────────────────────────

export interface ScanRequest {
  /** The raw URL submitted by the user */
  url: string;
}

// ── Individual phishing check results ────────────────────────────────────────

export interface PhishingChecks {
  /** true if the URL uses HTTPS */
  https: boolean;

  /** true if the domain is a raw IP address (e.g. http://192.168.1.1/login) */
  ipAddress: boolean;

  /** true if the URL goes through a known shortener (bit.ly, t.co, …) */
  urlShortener: boolean;

  /** true if the full URL exceeds the safe-length threshold */
  longUrl: boolean;

  /**
   * List of phishing keywords found in the URL path/query (NOT in a trusted domain).
   * Brand names (google, paypal…) are no longer included here — see brandImpersonation.
   */
  suspiciousKeywords: string[];

  /** true if the TLD is on the high-risk list */
  suspiciousTld: boolean;

  /** true if the hostname has more sub-domains than considered normal */
  manySubdomains: boolean;

  /** raw count of hyphens found in the hostname */
  hyphenCount: number;

  /** true if the URL contains percent-encoded characters (%xx) */
  hasEncodedChars: boolean;

  /**
   * Populated when the hostname appears to impersonate a trusted brand.
   * e.g. { brand: 'paypal', hostname: 'paypal-update-account.tk' }
   * null when no impersonation is detected or the domain is the real brand.
   */
  brandImpersonation: BrandImpersonationResult | null;

  /**
   * true when the exact domain (or a valid subdomain) is on the trusted list.
   * When true, brand-name keywords do NOT contribute to the score.
   */
  isTrustedDomain: boolean;

  /**
   * Result from the domain reputation layer (placeholder until an external
   * API such as Google Safe Browsing / VirusTotal is wired in).
   */
  reputation: ReputationResult;
}

// ── Brand impersonation detail ────────────────────────────────────────────────

export interface BrandImpersonationResult {
  /** The brand being impersonated, e.g. "paypal" */
  brand: string;
  /** The full hostname as detected, e.g. "paypal-update-account.tk" */
  hostname: string;
}

// ── Domain reputation (pluggable layer) ───────────────────────────────────────

export type ReputationStatus =
  | 'unknown'     // not checked / no API configured
  | 'clean'       // API confirmed safe
  | 'malicious'   // API confirmed malicious
  | 'suspicious'; // API flagged as suspicious

export interface ReputationResult {
  status: ReputationStatus;
  /** Source that produced this verdict, e.g. "google-safe-browsing" */
  source: string | null;
  /** Human-readable note or reason from the reputation provider */
  detail: string | null;
}

// ── Risk classification ───────────────────────────────────────────────────────

export type RiskLevel = 'Safe' | 'Suspicious' | 'Dangerous';

// ── Score breakdown (explainability) ─────────────────────────────────────────

/**
 * Describes the contribution of a single signal to the aggregate risk score.
 * The array of these is returned alongside the numeric score so the frontend
 * (and audit trail) can show exactly why a URL scored as it did.
 */
export interface ScoreContribution {
  /** Machine-readable signal identifier, e.g. "noHttps", "brandImpersonation" */
  signal: string;
  /** Human-readable description of what was detected */
  description: string;
  /** Points this signal contributed to the total score (can be negative for discounts) */
  points: number;
  /** Severity classification for UI display */
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
}

// ── Full API response ─────────────────────────────────────────────────────────

export interface ScanResponse {
  /** The URL that was analysed */
  url: string;

  /** Aggregate risk score 0–100 */
  riskScore: number;

  /** Human-readable risk band */
  riskLevel: RiskLevel;

  /** Individual check results */
  checks: PhishingChecks;

  /**
   * Per-signal score breakdown explaining how the aggregate score was reached.
   * Each entry names the signal, describes what was detected, and states how
   * many points it contributed. Used by the frontend to show explainable scoring.
   */
  scoreBreakdown: ScoreContribution[];

  /**
   * Specific, actionable recommendations — one entry per triggered check.
   * Replaces the single generic recommendation string.
   * Always has at least one entry.
   */
  recommendations: string[];

  /**
   * Legacy single-string recommendation kept for frontend compatibility.
   * Set to recommendations[0] when multiple items exist.
   */
  recommendation: string;

  /**
   * Plain-language AI explanation generated by Gemini after the rule engine
   * has finished. The AI only explains — it does not change the score or level.
   *
   * Set to a dynamic deterministic explanation derived from the scan signals
   * if Gemini fails, times out, or GEMINI_API_KEY is not configured.
   * Never undefined — always a non-empty string.
   */
  aiExplanation: string;

  /**
   * Identifies which layer produced the explanation.
   *
   * "gemini"       — Gemini returned a successful response within the timeout.
   * "deterministic" — Gemini was unavailable, timed out, or returned an error;
   *                   the explanation was built from the rule-engine signals.
   *
   * The frontend can use this to label the explanation source (e.g.
   * "AI explanation" vs "Rule-based explanation").
   */
  aiExplanationProvider: 'gemini' | 'deterministic';
}
