/**
 * services/urlScannerService.ts
 * ─────────────────────────────
 * HTTP client layer between the React app and the Express backend.
 *
 * Responsibilities:
 *  1. POST the URL to /api/scan
 *  2. Normalise the backend response shape into the ScanResult type
 *     that ResultCard and the rest of the frontend already understand
 *  3. Classify every failure into a user-friendly error message
 *
 * The backend and frontend agree on the contract but differ in two details:
 *  - riskLevel:  backend → "Safe"|"Suspicious"|"Dangerous"  (title-case)
 *                frontend → "safe"|"suspicious"|"dangerous"  (lower-case)
 *  - checks:     backend → PhishingChecks object with named boolean/number fields
 *                frontend → SecurityCheck[] array with {label, value, passed}
 *  - verdict:    backend → "recommendation" field
 *                frontend → "verdict" field
 *  - scannedAt:  not returned by the backend → stamped client-side
 */

import axios, { AxiosError } from 'axios';
import type { ScanResult, SecurityCheck, RiskLevel } from '@/types/dashboard';

// ─────────────────────────────────────────────────────────────────────────────
// Backend response types (mirrors backend/src/models/scan.model.ts)
// ─────────────────────────────────────────────────────────────────────────────

/** The raw object the backend puts inside `checks` */
interface BackendPhishingChecks {
  https: boolean;
  ipAddress: boolean;
  urlShortener: boolean;
  longUrl: boolean;
  suspiciousKeywords: string[];
  suspiciousTld: boolean;
  manySubdomains: boolean;
  hyphenCount: number;
  hasEncodedChars: boolean;
}

/** The full JSON body returned by POST /api/scan */
interface BackendScanResponse {
  url: string;
  riskScore: number;
  riskLevel: 'Safe' | 'Suspicious' | 'Dangerous';
  checks: BackendPhishingChecks;
  recommendation: string;
  recommendations: string[];
  /**
   * Plain-language AI explanation generated by Gemini on the backend.
   * Always present — set to the fallback message if Gemini is unavailable.
   */
  aiExplanation: string;
}

/** The JSON body returned when the backend sends a 4xx/5xx error */
interface BackendErrorResponse {
  error: string;
  message: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Axios instance
// ─────────────────────────────────────────────────────────────────────────────

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:5000/api';

const apiClient = axios.create({
  baseURL: API_BASE_URL,
  timeout: 15_000, // 15 s — surface a timeout before the browser gives up
  headers: {
    'Content-Type': 'application/json',
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// Response normalisation helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Convert the backend's title-case risk level to the frontend's lower-case
 * union type expected by RiskBadge, ResultCard, and the colour maps.
 */
function normaliseRiskLevel(level: BackendScanResponse['riskLevel']): RiskLevel {
  return level.toLowerCase() as RiskLevel;
}

/**
 * Expand the flat PhishingChecks object into the ordered SecurityCheck[]
 * array that ResultCard renders as a table.
 *
 * Each entry describes one check:
 *  - label  → human-readable name shown in the table
 *  - value  → string representation of the result
 *  - passed → drives the green ✓ / red ✗ icon
 */
function buildSecurityChecks(c: BackendPhishingChecks): SecurityCheck[] {
  return [
    {
      label: 'HTTPS',
      value: c.https ? 'Enabled' : 'Not enabled',
      passed: c.https,
    },
    {
      label: 'IP Address URL',
      value: c.ipAddress ? 'Yes — suspicious' : 'No',
      passed: !c.ipAddress,
    },
    {
      label: 'URL Shortener',
      value: c.urlShortener ? 'Detected' : 'Not detected',
      passed: !c.urlShortener,
    },
    {
      label: 'URL Length',
      value: c.longUrl ? 'Unusually long' : 'Normal',
      passed: !c.longUrl,
    },
    {
      label: 'Suspicious Keywords',
      value:
        c.suspiciousKeywords.length > 0
          ? c.suspiciousKeywords.slice(0, 3).join(', ')
          : 'None',
      passed: c.suspiciousKeywords.length === 0,
    },
    {
      label: 'Suspicious TLD',
      value: c.suspiciousTld ? 'High-risk TLD detected' : 'Normal',
      passed: !c.suspiciousTld,
    },
    {
      label: 'Subdomains',
      value: c.manySubdomains ? 'Excessive' : 'Normal',
      passed: !c.manySubdomains,
    },
    {
      label: 'Hyphens in Domain',
      value: String(c.hyphenCount),
      // More than 3 hyphens is considered suspicious
      passed: c.hyphenCount <= 3,
    },
    {
      label: 'Encoded Characters',
      value: c.hasEncodedChars ? 'Detected (%xx)' : 'None',
      passed: !c.hasEncodedChars,
    },
  ];
}

/**
 * Map a raw BackendScanResponse into the ScanResult shape that
 * the entire frontend (ResultCard, RecentScansTable, etc.) already uses.
 */
function mapToScanResult(raw: BackendScanResponse): ScanResult {
  return {
    url: raw.url,
    riskScore: raw.riskScore,
    riskLevel: normaliseRiskLevel(raw.riskLevel),
    verdict: raw.recommendation,
    checks: buildSecurityChecks(raw.checks),
    scannedAt: new Date().toISOString(),
    aiExplanation: raw.aiExplanation,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Error classification
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Turn any thrown value into a clean, user-facing string.
 *
 * Priority:
 *  1. Axios timeout → friendly timeout message
 *  2. Network error (ECONNREFUSED etc.) → server offline message
 *  3. 4xx with a message body → surface the backend's own message
 *  4. 5xx → generic server error message
 *  5. Anything else → fallback
 */
function classifyError(err: unknown): string {
  if (!axios.isAxiosError(err)) {
    return 'An unexpected error occurred. Please try again.';
  }

  const axiosErr = err as AxiosError<BackendErrorResponse>;

  // Timeout
  if (axiosErr.code === 'ECONNABORTED' || axiosErr.message.toLowerCase().includes('timeout')) {
    return 'The scan request timed out. Please check your connection and try again.';
  }

  // No response at all — server is offline or unreachable
  if (!axiosErr.response) {
    return 'Cannot reach the scan server. Make sure the backend is running on port 5000.';
  }

  const { status, data } = axiosErr.response;

  // 400 — invalid URL or validation error from backend
  if (status === 400) {
    return data?.message ?? 'Invalid URL. Please enter a valid http:// or https:// address.';
  }

  // 429 — rate limited
  if (status === 429) {
    return 'Too many requests. Please wait a moment and try again.';
  }

  // 5xx — backend crashed
  if (status >= 500) {
    return 'The scan server encountered an error. Please try again later.';
  }

  // Fallback for any other HTTP error
  return data?.message ?? `Unexpected error (HTTP ${status}). Please try again.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Scan a URL for phishing indicators.
 *
 * @param url  The raw URL string entered by the user
 * @returns    A fully mapped ScanResult ready for ResultCard
 * @throws     A user-friendly string on any failure
 */
export async function scanUrl(url: string): Promise<ScanResult> {
  try {
    const { data } = await apiClient.post<BackendScanResponse>('/scan', { url });
    return mapToScanResult(data);
  } catch (err) {
    // Re-throw as a plain string so the caller (ScannerCard) can set it
    // directly into its error state without any extra unwrapping.
    throw classifyError(err);
  }
}
